from app.schemas.common import (
    BaseSchema,
    PaginationParams,
    PaginatedResponse,
    SuccessResponse,
    ErrorResponse,
    HealthCheckResponse,
    TimestampMixin,
    IDMixin,
)

from app.schemas.auth import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    Token,
    TokenPayload,
    LoginRequest,
    RegisterRequest,
    RefreshTokenRequest,
    PasswordChangeRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    APIKeyCreate,
    APIKeyResponse,
    APIKeyFullResponse,
)

from app.schemas.project import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectSettings,
    ProjectResponse,
    ProjectListResponse,
    ProjectStatsResponse,
)

from app.schemas.scan import (
    ScanRequest,
    ScanConfig,
    ScanResponse,
    ScanJobBase,
    ScanJobResponse,
    ScanJobListResponse,
    ScanJobDetailResponse,
    ScanCancelRequest,
    ScanLogsRequest,
    ScanLogEntry,
    ScanLogsResponse,
    ScanStageProgress,
    ScanProgressResponse,
)

from app.schemas.result import (
    SubdomainResult,
    EndpointResult,
    VulnerabilityResult,
    JsFileResult,
    ScanResultsResponse,
    AttackSurfaceGraph,
    AggregatedStats,
)

from app.schemas.insight import (
    AiInsightBase,
    AiInsightCreate,
    AiInsightUpdate,
    AiInsightResponse,
    AiInsightListResponse,
    AiAnalysisReport,
    RiskScoreBreakdown,
    AttackVector,
)

__all__ = [
    "BaseSchema",
    "PaginationParams",
    "PaginatedResponse",
    "SuccessResponse",
    "ErrorResponse",
    "HealthCheckResponse",
    "TimestampMixin",
    "IDMixin",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "RegisterRequest",
    "RefreshTokenRequest",
    "PasswordChangeRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "APIKeyCreate",
    "APIKeyResponse",
    "APIKeyFullResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectSettings",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectStatsResponse",
    "ScanRequest",
    "ScanConfig",
    "ScanResponse",
    "ScanJobBase",
    "ScanJobResponse",
    "ScanJobListResponse",
    "ScanJobDetailResponse",
    "ScanCancelRequest",
    "ScanLogsRequest",
    "ScanLogEntry",
    "ScanLogsResponse",
    "ScanStageProgress",
    "ScanProgressResponse",
    "SubdomainResult",
    "EndpointResult",
    "VulnerabilityResult",
    "JsFileResult",
    "ScanResultsResponse",
    "AttackSurfaceGraph",
    "AggregatedStats",
    "AiInsightBase",
    "AiInsightCreate",
    "AiInsightUpdate",
    "AiInsightResponse",
    "AiInsightListResponse",
    "AiAnalysisReport",
    "RiskScoreBreakdown",
    "AttackVector",
]